### ISSUE TITLE
cannot import name QUERY_TERMS

### ISSUE THREAD

**Issue by satyaakam** [OpenMOOC/moocng#18]
i am trying to run a developer version , i will be frank i am not following the exact steps mentioned in the doc , just want a developer version running first , i am trying to use sqllite instead of Mysql or Postgresql 

the steps i am following are 

1) running in virtualenv
2) python setup.py develop
3) manage.py runserver

after this when i visit http://localhost:8000/

i am getting the error 
Exception Type: ImportError at /
Exception Value: cannot import name QUERY_TERMS

here is a traceback http://dpaste.de/bwkbh/

TIA
-Satya

**Comment by lorenzogil** [comment]
As mentioned in the install documentation, you need to use our own version of Tastypie for the moment:

https://github.com/OpenMOOC/moocng/blob/master/docs/source/install.rst#tastypie

We want to upgrade to latest Tastypie official version which was released recently and which fix the issues we had with Tastypie when we forked it.

By the way, I assume there is a 4th step in your procedure which involves running a syncdb --migrate to create the database schema.

**Comment by satyaakam** [comment]
yes the third step is the syncdb which i missed in the list , 

i am still getting the same errror http://dpaste.de/CaMbX/

-satya

**Comment by fid-jose** [comment]
According to your comment, you are using django 1.5.
I don't think OpenMOOC works with django 1.5, I advise you to install django 1.4.1.

**Comment by lorenzogil** [comment]
You are still using the old Tastypie, not OpenMOOC Tastypie. Our Tastypie has this line:

from django.db.models.sql.constants import QUERY_TERMS, LOOKUP_SEP

instead of

from django.db.models.constants import QUERY_TERMS, LOOKUP_SEP

https://github.com/OpenMOOC/django-tastypie/blob/0.9.11_no_related_saved/tastypie/resources.py

**Comment by satyaakam** [comment]
i cleaned up everything 

now i am getting the following error http://dpaste.de/GBkRg/

Exception Type: ImportError at /
Exception Value: cannot import name LOOKUP_SEP

**Comment by ablanco** [comment]
@satyaakam Is this import error still happening to you? Since you have opened another issue with the mongodb connection problem I guess this is not happening anymore.

**Comment by satyaakam** [comment]
well it is still there i gave up on it after no response from anyone , if running a local instance is so much PITA :-) , how am i going to use it in production?

**Comment by ablanco** [comment]
@satyaakam Have you tried it with Django 1.4? As fid-jose told you, this project requires Dajngo 1.4, not Django 1.5, and in your dpaste it still says your Django version is 1.5.

**Comment by satyaakam** [comment]
when i run easy_install moocng , it should take care of the version or does it not ? let me check the version after i run the easy_install command

its taking forever to install with the command python setup.py  develop stuck at the following package will try in later again :-)

Installed /var/www/moocng/moocng
Processing dependencies for moocng==0.0
Searching for django-compressor==1.1.2
Reading http://pypi.python.org/simple/django_compressor/

**Comment by ablanco** [comment]
@satyaakam there is no release of moocng yet, so it has to be deployed using setup.py develop or setup.py install.

The dependencies' versions are frozen in the setup.py. If one of them takes a lot to be downloaded might be that pypi is down or having problems with some packages. You may have to wait until pypi is back onlie again or use a pypi mirror.

**Comment by satyaakam** [comment]
Yes trying with python setup develop now will update how it does

**Comment by pitbulk** [comment]
@satyaakam , Is the problem solved?

**Comment by satyaakam** [comment]
closing this one too may be ask around on dev list

**Comment by Hyperion101010** [comment]
it also happens with me 
tells me that it canot import query_terms from database when i make resource of it 
simply following tutorials :) please work on this
