### ISSUE TITLE
Still error with install DOC

### ISSUE THREAD

**Issue by satyaakam** [OpenMOOC/moocng#22]
Hi ,
      i get the following http://dpaste.de/SYCa0/ errors  after trying the install doc from here https://raw.github.com/OpenMOOC/moocng/master/docs/source/install.rst

-Satya

**Comment by jespino** [comment]
Have you MongoDB installed and configured?

**Comment by johnfelipe** [comment]
I get python 2.4 no 2.7 follow install instructions

Please Help

**Comment by ablanco** [comment]
@johnfelipe openmooc requires python 2.6 or 2.7, it doesn't work with python 2.4

**Comment by johnfelipe** [comment]
Hi, please tell me  /var/www/moocng/lib/python2.7/site-packages/moocng-X.Y.Z-py2.7.egg/moocng/local_settings.py, still appear.

It need install MongoDB? or with postgresql is enough?

Tnks

**Comment by satyaakam** [comment]
@jespino i am trying with Sqlite  @johnfelipe you too can try with Sqlite once it runs then we can think of it

**Comment by ablanco** [comment]
@johnfelipe @satyaakam It requires postgresql and mongodb, both of them. It may work with sqlite instead of postgresql, but we haven't tried it, so you are entering uncharted territory there :)

**Comment by satyaakam** [comment]
ok maye be its first lets see how far i can go.

**Comment by satyaakam** [comment]
ok let me update this ticket only now i get the following error "cannot import name LOOKUP_SEP"

http://dpaste.de/FhXCN/

**Comment by johnfelipe** [comment]
i update python to 2.7 and install postgre and mongo db, but i dont find  /var/www/moocng/lib/python2.7/site-packages/moocng-X.Y.Z-py2.7.egg/moocng/local_settings.py, please help me with that

TNks

**Comment by johnfelipe** [comment]
i delete all and make new and i get /var/www/moocng/lib/python2.7/site-packages/moocng-0.0-py2.7.egg/moocng
but file local setting is not, i create it with:

vim /var/www/moocng/lib/python2.7/site-packages/moocng-0.0-py2.7.egg/moocng/local_settings.py

and insert:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'moocng',
        'USER': 'moocng',
        'PASSWORD': 'secret',
        'HOST': '',
        'PORT': '',
    }
}

(change pwd with user moocng)

Then, activate the virtualenv:

$ source /var/www/moocng/bin/activate
And run the Django syncdb command to create the database schema:

$ django-admin.py syncdb --settings=moocng.settings --migrate

and get this error:

OperationalError: FATAL:  Ident authentication failed for user "moocng"

**Comment by johnfelipe** [comment]
Hi again:

in var/lib/pgsql/data/pg_hba.conf

local   all all trust
host    all 127.0.0.1/32    trust
local    moocng      moocng                         md5

but i get new error:

![errorDjango syncdb](https://f.cloud.github.com/assets/428820/305845/4b26b454-9665-11e2-87e8-176f64ae20a9.png)

**Comment by johnfelipe** [comment]
Hi i need upgrade postgresql

But i get other error with askbot, please help in https://github.com/OpenMOOC/askbot-openmooc/issues/4

Tnks

**Comment by pitbulk** [comment]
@satyaakam You solved the problem?

**Comment by satyaakam** [comment]
@pitbulk no not yet will look into it latter

**Comment by satyaakam** [comment]
No matter what i try i land up with this error 

"cannot import name LOOKUP_SEP"

http://dpaste.de/zv0id/

**Comment by ablanco** [comment]
@satyaakam There says you are using Django 1.5, and it must be Django 1.4

**Comment by satyaakam** [comment]
ok sucess now , now i have a running instances on all the three DB's MySQL , PostGRES, and SQLite , let me document it when its fresh.

thanks for all the help

-Satya

**Comment by ablanco** [comment]
@satyaakam I'm closing the issue due to your success.
